# Generated by Django 5.1.2 on 2024-10-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astnode',
            name='rule_expression',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='astnode',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
