# Generated by Django 5.1.2 on 2024-10-19 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0002_astnode_rule_expression_alter_astnode_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astnode',
            name='left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_node', to='rule_engine.astnode'),
        ),
        migrations.AlterField(
            model_name='astnode',
            name='right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_node', to='rule_engine.astnode'),
        ),
        migrations.AlterField(
            model_name='astnode',
            name='rule_expression',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='astnode',
            name='type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='astnode',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
