# Generated by Django 5.1.2 on 2024-10-19 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0003_alter_astnode_left_alter_astnode_right_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astnode',
            name='left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_child', to='rule_engine.astnode'),
        ),
        migrations.AlterField(
            model_name='astnode',
            name='right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_child', to='rule_engine.astnode'),
        ),
        migrations.AlterField(
            model_name='astnode',
            name='rule_expression',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='astnode',
            name='type',
            field=models.CharField(choices=[('operator', 'Operator'), ('operand', 'Operand')], max_length=10),
        ),
        migrations.AlterField(
            model_name='astnode',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
